#!/usr/bin/env bash
# Displays Information about subdomains

# Usage:
# (1) ./0-world_wide_web 3akare.tech
# (2) ./0-world_wide_web 3akare.tech web-02

get_record_info() {
    local domain="$1"
    local sub_domain="$2"

    record_type=$(dig "$sub_domain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
    ip_address=$(dig "$sub_domain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
    echo "The subdomain $sub_domain is a $record_type record and points to $ip_address"
}

if [ "$#" = 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub_domain in "${subdomains[@]}"; do
        get_record_info "$1" "$sub_domain"
    done
elif [ "$#" = 2 ]; then
    get_record_info "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
