#!/usr/bin/env bash
[mysqld]
datadir=/var/lib/mysql
socket=/var/run/mysqld/mysqld.sock
log-error=/var/log/mysql/error.log
pid-file=/var/run/mysqld/mysqld.pid
bind-address=0.0.0.0 # Commented out to allow connections from any IP
server-id=1
log_bin=/var/log/mysql/mysql-bin.log

